server:
  port: 8080

spring:
  application:
    name: jobspoon

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/${DATABASE_NAME:aim_db}
    username: ${DATABASE_USER:eddi}
    password: ${DATABASE_PASSWORD:eddi@123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:eddi@123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework: INFO



##Oauth 부분 (임시)
kakao:
  login-url: https://kauth.kakao.com
  withdraw-url: https://kapi.kakao.com/v1/user/unlink
  client-id: a7bde7555c7aeefe1ea671e245702605
  redirect-uri: http://localhost:8080/oauth/kakao/callback
  token-request-uri: https://kauth.kakao.com/oauth/token
  user-info-request-uri: https://kapi.kakao.com/v2/user/me
